### ISSUE TITLE
尋找失蹤雞口

### ISSUE THREAD

**Issue by haha861924** [LINDuke-Lin/Cpp-Exercise#2]
我在找一隻雞
請問你有看到他嗎?
他已經失蹤快一個月了

**Comment by zoeGuava** [comment]
![image](https://user-images.githubusercontent.com/49506360/174000059-506c9eec-b3d2-4c1d-83af-a0e0b6320fdc.png)

**Comment by beareatapple** [comment]
雞雞!!  I miss him QQ

**Comment by calvin0310** [comment]
出來面對

**Comment by LonelyYeezhiChicken** [comment]
![image](https://user-images.githubusercontent.com/61058224/174037514-784514c1-bfa7-4bb5-94c6-b1179f8aae2b.png)

**Comment by alphatero** [comment]
想雞惹
